### PR TITLE
Set of enhancements to the BetterUI addon (see description for details)

### PR DESCRIPTION
**Pull request by trentapple**
This batch of changes includes enhancements to the guild store related interfaces, the bank, as well as overall UI enhancements to improve interoperability with other addons (such as Wykkd Toolbar) -- it also fixes a few issues within the addon.

## A summary of just a few of the new enhancements / features include:
- Item bind protection -- configurable option within inventory settings (i.e. when enabled it will prompt you before equiping a "Bind on Equip" item -- this works on all equippable item types including rings / 1H items and works using either the keybinding or the action menu for equiping the item)
- Tel Var uses the appropriate currency texture when depositing or withdrawing it from Enhanced Bank.
- Added "Unknown Recipe" icon next to attribute icons for any Unknown Recipes to easily identify which provisioning recipes are known / unknown in any list (displays on Enhanced Bank, Guild Store, Inventory, etc.)
- Added "Trading Guild / Market" icon next to attribute icons to indicate if the item meets the criteria to be listed on a guild store (i.e. if the item is sellable)
- Fixes to the "Create Listing" / "Sell" panel of the Guild Store (it does not display LOCKED, stolen, bound, or BoP items -- it also now displays the attribute icons next to the item name)
- Ability to search in the guild store filter / browse by Unknown Recipes: "Both" (default), "Yes", or "No"
- Guild Store Browse automatically advances to the next page if the current page is empty and there are more pages.
- Added "Mark as Junk" (if junk feature is enabled) as keybind which displays for any junkable item (i.e. the keybind will not be visible if you are selecting an item that is "LOCKED"
- Improved Lock / Unlock support in addition to the icon which is displaying to the left of any items that are locked.
- **_And many more enhancements._**.. I use this all for myself personally (and rely on this version of BetterUI every day), but need to get these enhancements / fixes integrated in some form or another into the main release because I know others would like to enjoy / utilize them as well.

### CODE REVIEW

**Comment by prasoc** [comment]
Wow 55 commits in a pull request? Thank you very much for your contribution, I'm sure a lot of people will be happy with your work - I will work through the files changed and pull the features in, hopefully later on today 

prasoc

**Comment by trentapple** [comment]
Thank you. Please let me know if you have any questions or if there is anything I can help with further!

**Comment by prasoc** [comment]
I have scanned the changes and they do fit in with the code style and fit seamlessly into BetterUI. Thank you for the major fixes and improvements, they will be added to a new version releasing soon (after my exams, support is always time-consuming!)

prasoc

**Comment by j-blandford** [comment]
I have scanned the changes and they do fit in with the code style and fit seamlessly into BetterUI. Thank you for the major fixes and improvements, they will be added to a new version releasing soon (after my exams, support is always time-consuming!)

prasoc

**Comment by trentapple** [comment]
I am glad I can help contribute 👍 

Good luck on your exams!

**Pull request merged**
